namespace :dummy do
  desc "Hydrate the database with some dummy data to make it easier to develop"
  task :reset => :environment do
    
 starting = Time.now


    User.create([
      {id: 1, email: "knott.kantachuvesiri@kellogg.northwestern.edu", username: "Knott", password: "password", created_at: "2015-01-19 09:24:34"}
     
    ])

    Civ.destroy_all
    Civ.create([
{id: 1, name:"American", unique_unit:"P-51 Mustang", unique_infrastructure:"Film Studio", description:"In terms of civilization, the progress of America from a collection of squabbling colonies to a globe-spanning superpower has been meteoric. Product of waves of immigration, it is currently the world’s fourth largest country and third most populous, spanning the width of the North American continent from Atlantic to Pacific and site of some of humanity’s greatest cities. With the world’s largest GDP (gross domestic product), service sector, media industry, and military GFP (global firepower factor, not including nuclear weaponry), America could be considered the world’s foremost – or at least most influential – current civilization.", civ_ability:"Founding Fathers", created_at:"2015-04-24 01:26:47"},
{id: 2, name:"Arabian", unique_unit:"Mamluk", unique_infrastructure:"Madrasa", description:"A few months after his farewell pilgrimage – thereby laying the foundation for the Hajj – the Prophet Muhammed at the age of 62 fell ill and died in Medina in June 632 AD. According to Sunni writ, his followers chose Abu Bakr Siddique as Amir al-Mu’minin (“Commander of the Faithful”), Muhammed’s successor and first of the Rashidun caliphs. Shi’a Muslims hold, instead, that Ali, son-in-law and cousin to the Prophet, was Muhammed’s own selection as his spiritual and temporal successor, thus setting off a schism that continues today.", civ_ability:"The Last Prophet", created_at:"2015-04-24 01:26:47"},
{id: 3, name:"Australian", unique_unit:"Digger", unique_infrastructure:"Outback Station", description:"Settled in turn by Aboriginals, convicts, paupers, prospectors, and bushrangers, the land “down under” was first occupied by people around 45 thousand years ago when some managed to migrate through the Indonesian islands and reach the northern shore of the continent. There these hunter-gathers prospered in isolation, with a rich oral and spiritual culture, until 1770 AD when James Cook sailed along the coast and claimed the whole place for Great Britain. Captain Cook wasn’t the first to bump into Australia—the Dutchman Willem Janszoon and Englishman William Dampier had done so far earlier—but he was the first to see opportunity in a remote and dangerous land.", civ_ability:"Land Down Under", created_at:"2015-04-24 01:26:47"},
{id: 4, name:"Aztec", unique_unit:"Eagle Warrior", unique_infrastructure:"Tlachtli", description:"When Hernando Cortes and his band of ne’er-do-wells arrived, the Aztec Empire was still in its childhood, having come into existence (more-or-less) around 1428 AD. Although the Excan Tlahtoloyan (Aztec Empire) lasted only one hundred years, it was an eventful one hundred years.", civ_ability:"Legend of the Five Suns", created_at:"2015-04-24 01:26:47"},
{id: 5, name:"Brazilian", unique_unit:"Minas Geraes", unique_infrastructure:"Street Carnival / Copacabana ", description:"Paulo Coelho, Brazil’s greatest novelist, wrote of his people, “They were seeking out the treasure of their destiny, without actually wanting to live out their destiny.” Although the Brazilians enjoy the world’s seventh largest (and still growing) economy, a diverse cultural stew, the continent’s best standard of living, and one of the planet’s greatest eco-systems, they are known by most as the “ultimate party animals.” However justified that preconception might be today, Brazil’s past has been anything but a Carnival. In fact, most of it has been downright grim.", civ_ability:"Amazon", created_at:"2015-04-24 01:26:47"},
{id: 6, name:"Canadian", unique_unit:"Mountie", unique_infrastructure:"Ice Hockey Rink", description:"There have been people living in Canada since before recorded time. Archaeological evidences shows the first groups of hunters crossed into Canada from Siberia during the Wisconsin glaciation, then spread east and southward over time. As the climate stabilized, the indigenous groups diversified and specialized to their geographic regions. These aboriginal inhabitants (now called “First Nations” in Canada) included nations as diverse as the Cree, Hopewell, Inuit, Tlingit, Ojibwa, Haida, and Mi'kmaq, as well as countless other bands and nations over the ages.", civ_ability:"Four Faces of Peace", created_at:"2015-04-24 01:26:47"},
{id: 7, name:"Chinese", unique_unit:"Crouching Tiger", unique_infrastructure:"Great Wall", description:"China has contributed much to civilization: paper, the bell, the fishing reel, gunpowder, the compass, the bulkhead, playing cards, the oil well, woodblock printing, silk, the list of Chinese inventions goes on endlessly. China has also given civilization great religions (Confucianism, Taoism, Faism, Yi Bimoism, and others) and great philosophies (mohism, legalism, naturalism, neo-taoism and so forth). Chinese authors such as Shi Nai’an and Wu Cheng’an, artists such as Han Gan and Ma Yuan, composers such as Wei Liangfu and Cai Yan enriched civilization beyond measure. Moreover, China introduced the concepts of slavery, monogamy, espionage, subversion, propaganda, urbanization, lingchi (“death by a thousand cuts”), and more.", civ_ability:"Dynastic Cycle", created_at:"2015-04-24 01:26:47"},
{id: 8, name:"Cree", unique_unit:"Okihtcitaw", unique_infrastructure:"Mekewap", description:"They call themselves Nehiyawak. The Cree (as they are called in English) are Canada’s largest First Nation today. Their traditional territory is primarily in the Subarctic and Plains regions of the modern provinces of Alberta, Saskatchewan, Manitoba, and Ontario, following along the Southwestern shore of Hudson Bay, and extending into portions of Quebec. Divided into regional and dialectal subgroups, and composed of dozens of individual bands and joined by a common Algonquian language, the Cree are closely related to a number of other First Nations, blending with those people and with outsiders over the course of their history through a policy of welcoming outsiders.", civ_ability:"Nîhithaw", created_at:"2015-04-24 01:26:47"},
{id: 9, name:"Dutch", unique_unit:"De Zeven Provinciën", unique_infrastructure:"Polder", description:"The Netherlands never let their small size get in the way of progress. Dutch persistence and ingenuity led to a distinct culture that is more than just wooden shoes, tulips, windmills, and the color orange. When they needed more land, the Netherlands pushed back the tides of the North Sea and reclaimed the ocean floor. Their formidable ships would reach far beyond Dutch shores as they built an empire based entirely around trade.", civ_ability:"Grote Rivieren", created_at:"2015-04-24 01:26:47"},
{id: 10, name:"Egyptian", unique_unit:"Maryannu Chariot Archer", unique_infrastructure:"Sphinx", description:"When the Greeks were still bashing each other in the head with rocks and Rome wasn’t even a gleam in anyone’s eye, Pharaonic Egypt had already established a civilization along the banks of the River Nile to stand the test of time … well, at least a few millennia. Until absorbed by mighty Rome, around 170 successive pharaohs had ruled the fertile lands. As might be expected at the dawn of history, in the beginning a bunch of “barbarians” found the living relative easier along the river (at that time, the region was dominated by savanna rather than arid desert) than elsewhere; within a few generations they had founded some farming villages and a power base at the city of Hierakonpolis and later Abydos. Coincidentally, these Naqada also founded the first Egyptian dynasty.", civ_ability:"Iteru", created_at:"2015-04-24 01:26:47"},
{id: 11, name:"English", unique_unit:"Sea Dog", unique_infrastructure:"Royal Navy Dockyard", description:"Until the Normans put an end to all the foolishness, the “Sceptered Isle” had been invaded by anyone who could row a boat: Celts, Bretons, Angles, Romans, Saxons, Vikings and sundry. The kingdom of Britain can be reliably dated from their arrival during the “Norman Invasion.” Others had tried to unite the squabbling nobility of England before; legendary Arthur had supposedly done so; William the Conqueror (also known to history as “William the Bastard” for assorted reasons) actually accomplished the task. Today, “Great” Britain (having overrun the kingdoms of Scotland and Wales) is one of the leaders of the European Union, world’s economy (ranking sixth), and humanity’s culture, home to about 64 million inhabitants.", civ_ability:"Workshop of the World", created_at:"2015-04-24 01:26:47"},
{id: 12, name:"French", unique_unit:"Garde Impériale", unique_infrastructure:"Chateau", description:"The French brought civilization haute cuisine, haute couture, haute-contre, and a whole lot of other “hautes.” But the French are not just about culture; they also brought history the Hundred Years' War, the Reign of Terror, Napoleon’s efforts to conquer Europe, etc.", civ_ability:"Grand Tour", created_at:"2015-04-24 01:26:47"},
{id: 13, name:"Georgian", unique_unit:"Khevsur", unique_infrastructure:"Tsikhe", description:"The Kingdom of Georgia, long considered the Golden Age of the Georgian people, existed for nearly 500 years at the crossroads of Central Asia. A bastion of Christianity, Georgia developed a distinctive, brilliant literary culture and art, and their unique alphabet is still used today. It was a diplomatic player in the affairs of the Holy Lands and Rus, an important ally of the Byzantine Empire, and the protector of a coterie of vassal states.", civ_ability:"Strength in Unity", created_at:"2015-04-24 01:26:47"},
{id: 14, name:"German", unique_unit:"U-Boat", unique_infrastructure:"Hansa", description:"There was no “Germany” – not until 1870 AD when Bismarck convinced the various bits that the good of the one outweighed the good of the many. Julius Caesar is the first known to have used the term Germania to refer to those barbaric lands across the Rhine from “peaceful” Gaul. Geographically, Germany stretched from the Rhine to the Vistula, from the Baltic to the Danube. As Caesar noted, the Gauls were warlike but could be civilized; the Teutoni, on the other hand, were just too savage and uncouth for anything but conquest. Perhaps he was right; with the collapse of the Roman Empire, all those uncouth tribes became “separate and independent gentes [peoples] and regna [kingdoms].” Nothing unified these save a common language (even though, given the dialects, some were virtually unintelligible to other Germans), common customs, and a common heritage of killing each other.", civ_ability:"Free Imperial Cities", created_at:"2015-04-24 01:26:47"},
{id: 15, name:"Greek", unique_unit:"Hoplite", unique_infrastructure:"Acropolis", description:"The Classical (often termed the Hellenic) Age of Greece begins with the death of the last Athenian tyrant in 510 BC and ends with the assassination of Phillip II of Macedonia in 336 BC. It is fitting that the period is defined by the deaths of great men, for it was a bloody time – marked by two extended wars, the decline of influential city-states, the rise of Macedonian hegemony. But those 174 years also saw Greece lay the foundations for Western civilization: the beginnings of empiricism, artistic aesthetics, political structures, literary forms and most of what constitutes culture. So it was an age of contrasts, and an iconic period and place in world history.", civ_ability:"Plato's Republic", created_at:"2015-04-24 01:26:47"},
{id: 16, name:"Hungarian", unique_unit:"Huszár", unique_infrastructure:"Thermal Bath", description:"For nearly a millennium, the Kingdom of Hungary was one of the major powers of Central Europe, central to the history and influence of the rulers and kingdoms of the region. Multiethnic and multilinguistic, the kingdom's cultural contributions and military history were critical to the interchange between Western and Eastern Europe. The kingdom is shot through with rivers, including the mighty Danube (which bisects Budapest), and includes the open plains of the Carpathian Basin, fringed with a few high ranges of mountains. Its thermal springs have attracted attention since the time of the Romans. Sitting astride the major cross-land routes of Europe, the Kingdom's strategic position made it a prize for royal houses and ambitious nobles alike.", civ_ability:"Pearl of the Danube", created_at:"2015-04-24 01:26:47"},
{id: 17, name:"Incan", unique_unit:"Warak'aq", unique_infrastructure:"Terrace Farm", description:"The Inca Empire was one of the last, largest, and powerful indigenous American nations. Its name in Quechua was “Tawantin Suyu”: The Four United Regions. It encompassed people speaking a variety of languages, had a strong central administrative body centered on the court, sophisticated public infrastructure and roads maintained by a system of compulsory labor, taxation and food distribution, and it did all of these without widespread use of written records, the wheel, or animal labor. As such, it presents students of history with a fascinating counterfactual case for evaluating claims linking political systems and technologies. In short, they're perfect to include in a game where you can build the Pyramids of Giza in Washington.", civ_ability:"Mit'a", created_at:"2015-04-24 01:26:47"},
{id: 18, name:"Indian", unique_unit:"Varu", unique_infrastructure:"Stepwell", description:"Until the British East India Company made their appearance, India was a mish-mash of competing city-states and small kingdoms ruled over by an assortment of nawabs, satraps, sultans, rajas, shahs, khans, nabobs, diwans, princes and various other feckless social climbers. There were dozens and dozens of these vest-pocket countries; for instance, what would later be the Punjab was composed of 34 “princely” states. Several empires had tried to unite the subcontinent into one banner before – Maurya, Chola, Pala, Gupta, Mughal, Maratha, and so forth – but failed. Seems profit rather than power was the key to making India whole.", civ_ability:"Dharma", created_at:"2015-04-24 01:26:47"},
{id: 19, name:"Indonesian", unique_unit:"Jong", unique_infrastructure:"Kampung", description:"At its height, the Buddhist-Hindu kingdom of Majapahit (in what is now Indonesia) flexed its might across 98 regional tributaries, a formidable state which once resisted the mighty Mongol Empire. Here, the monarch was not only its ruler, but its guardian, empowered by the people. But what if the people felt the leader no longer deserved being empowered?", civ_ability:"Great Nusantara", created_at:"2015-04-24 01:26:47"},
{id: 20, name:"Japanese", unique_unit:"Samurai", unique_infrastructure:"Electronics Factory", description:"After two thousand years of being insular and defensive, in two eventful centuries Japan has become one of the most industrious and influential civilizations, in terms of economics and culture. The folk who created ikebana (flower arranging), kabuki (dance-drama) and bushido (warrior-code) have also given the world manga, anime, sushi and sumo. The age-old traditions of Wa (usually translated as “harmony”) have been replaced, for better or worse, by those of progress and profit.", civ_ability:"Meiji Restoration", created_at:"2015-04-24 01:26:47"},
{id: 21, name:"Khmer", unique_unit:"Domrey", unique_infrastructure:"Prasat", description:"Between the Ninth and Fifteenth Centuries, the god-warrior-kings of the Khmer Empire dominated Southeast Asia. Theirs was a formidable agricultural-martial kingdom whose wealth impressed even the mighty Chinese to the North. Unfortunately, all of that gold and rice would prove too attractive for their regional rivals, ultimately making the conquerors of the Suvarnabhumi the conquered.", civ_ability:"Grand Barays", created_at:"2015-04-24 01:26:47"},
{id: 22, name:"Kongolese", unique_unit:"Ngao Mbeba", unique_infrastructure:"Mbanza", description:"According to legend, the foundations of the kingdom called Kongo lies in the troubles of the very large but not very rich tribal kingdom of Mpemba Kasi around the Kwilu Valley. The old wives’ tales that comprise “history” state that at some point weak Mpemba Kasi forged an alliance with its militaristic neighbor Mbata, eventually conquering the kingdom of Mwene Kabunga which lay upon a mountain plateau to the south. When the warrior Nimi a Lukeni merged all this territory he made M’banza Kongo, the village on the mountain, his capital. And so the Kingdom of Kongo was birthed c. 1390 AD – a kingdom that would at its peak control a territory that reached from Africa’s mid-Atlantic coast to the Kwango River, and from Pointe Noire in the north to the Loje River in the south.", civ_ability:"Nkisi", created_at:"2015-04-24 01:26:47"},
{id: 23, name:"Korean", unique_unit:"Hwacha", unique_infrastructure:"Seowon", description:"The Korean peninsula’s fate has long been one of struggle. Myriad dynasties rise, fall, and rise again on a landmass roughly the size of Great Britain. The influence of foreign empires, both supportive and belligerent, provide a constant uncertainty looming over the horizon.", civ_ability:"Three Kingdoms", created_at:"2015-04-24 01:26:47"},
{id: 24, name:"Macedonian", unique_unit:"Hypaspist", unique_infrastructure:"Basilikoi Paides", description:"According to legends generally accepted by the ancient Greeks and hardly anyone else, Macedon was founded by Hellenic emigrants from Argos who gradually expanded in the region around Mount Bermius. Perdiccas, one of the original colonists, was acknowledged as the first king of Macedon in founding the Argead dynasty. More likely, the original Macedones were barbarians from the north, distinct from the Hellenes, Thracians, and Illyrians around them, who happened to find a stretch of unoccupied terrain suitable for their goats.", civ_ability:"Hellenistic Fusion", created_at:"2015-04-24 01:26:47"},
{id: 25, name:"Mali", unique_unit:"Mandekalu Cavalry", unique_infrastructure:"Suguba", description:"The Kingdom, and later Empire of Mali was a remarkably long-lasting, pious, and rich empire, built on a foundation of trade between the Sahara, Sahel, and Subsaharan regions of Africa, unified by an Islamic faith, and administered capably by rulers for over 300 years. The Empire of Mali was at its height of power between the 13th and 16th Centuries, until it fractured under internal pressure and external threats.", civ_ability:"Songs of the Jeli", created_at:"2015-04-24 01:26:47"},
{id: 26, name:"Māori", unique_unit:"Toa", unique_infrastructure:"Marae", description:"Sometime during the 13th Century, people in canoes set off from somewhere in the Marquesas Islands in the South Pacific and headed south and west, until they arrived at the islands we call New Zealand, and which they called Aotearoa—the land of the long white cloud. The group would have used the sophisticated, traditional Polynesian navigational techniques to find this land, inferring its existence from cues and clues reflected in the natural world. They would have come ashore to a place where human beings had never settled, which had torn away from the mainland 100 million years previously, which had a unique and precious biome formed by ages of geological separation. It was a land of innumerable species of birds, including immense and flightless giants, terrifyingly large raptors, and shy bush dwellers. There were few land mammals and a few ancient genera of reptiles. The seas around the island teemed with life.", civ_ability:"Mana", created_at:"2015-04-24 01:26:47"},
{id: 27, name:"Mapuche", unique_unit:"Malón Raider", unique_infrastructure:"Chemamull", description:"Referred to as the Araucanos by the Spanish, a moniker thought to be rooted in their name for the region (and widely considered derogatory today), in the native language Mapuche means People of the Earth, and as the indigenous inhabitants of central Chile and parts of Argentina, these resilient natives survived countless incursions and hardships over the course of their nearly 2500-year history.", civ_ability:"Toqui", created_at:"2015-04-24 01:26:47"},
{id: 28, name:"Mongolian", unique_unit:"Keshig", unique_infrastructure:"Ordu", description:"At the height of their empire, the Mongols' wrath would be felt from East Asia to Western Europe, a dynasty which would live on well into the Twentieth Century. A true chronicle of their history must reconcile the horrors of the conquest with their skill in uniting the disparate parts of the empire from technology to culture.", civ_ability:"Örtöö", created_at:"2015-04-24 01:26:47"},
{id: 29, name:"Norwegian", unique_unit:"Berserker", unique_infrastructure:"Stave Church", description:"The Norwegian Vikings had a tendency to leave Norway. By 800 AD, they had colonized the Shetlands, Orkneys, Faroes, Hebrides and other places no one else much wanted. Around 820, they planted settlements on the west coast of Ireland, founding some of that island’s great cities (including Dublin). In or about 870 they discovered Iceland and promptly divvied it up between 400 chieftains. A hundred years later they showed up in Greenland, and Leif Ericson landed in North America c. 1000 AD (but didn’t stay long). During all this time, Norway itself wasn’t even unified, but rather made up of several petty kingdoms fighting it out.", civ_ability:"Knarr", created_at:"2015-04-24 01:26:47"},
{id: 30, name:"Nubian", unique_unit:"Pítati Archer", unique_infrastructure:"Nubian Pyramid", description:"Situated along the Great Bend of the Nile River in northern Africa, Nubia served as the gateway between the Red Sea and the Nile Delta—a locus of trade that could have spanned from the source of the Nile River to its mouth in the Mediterranean. Unfortunately for Nubia, the Egyptians directly to Nubia’s north had other ideas. The two civilizations would exchange roles as wary neighbor, conqueror, and vassal for millennia, until a series of invaders from distant lands permanently ended their rivalry.", civ_ability:"Ta-Seti", created_at:"2015-04-24 01:26:47"},
{id: 31, name:"Ottoman", unique_unit:"Barbary Corsair", unique_infrastructure:"Grand Bazaar", description:"For more than six centuries, the Ottoman Empire ruled the crossroads of Europe, Asia, and Africa, coming to rule a massive empire that stretched from Persia to the borders of Hungary and Poland, through the Middle East and across Northern Africa. Rising into power in a vacuum left behind by the Mongol invasions and the sweep of the Black Death, the Ottomans remained an empire until the aftermath of the first World War. During that time they were central to the political events in Europe and the Near East, ruling a fractious, multi-ethnic, multi-lingual, multi-religious empire.", civ_ability:"Great Turkish Bombard", created_at:"2015-04-24 01:26:47"},
{id: 32, name:"Persian", unique_unit:"Immortal", unique_infrastructure:"Pairidaeza", description:"At its height, the Persian Empire encompassed most of Mesopotamia, Asia Minor, the shores of the Black Sea, some of Central Asia (what would one day become Afghanistan), parts of the Caucasus mountains, Egypt, Thrace, and Macedon. For nearly two centuries, Persia had mastered the “cradle of civilization”—until a Macedone upstart named Alexander crushed the world's greatest power in less than four years.", civ_ability:"Satrapies", created_at:"2015-04-24 01:26:47"},
{id: 33, name:"Phoenician", unique_unit:"Bireme", unique_infrastructure:"Cothon", description:"The Phoenicians were not a nation-state in the usual sense, as much as a loose affiliation of independent maritime cities, typically ruled by kings and sharing a common cultural history. The Phoenicians were master traders and seafarers, and their system of writing forms the basis of most Western written systems. The term “Phoenician” is a Greek word. In the Bible they are referred to as the Caananites, from the Akkadian “Kinahna.” Modern archaeologists believe they referred to themselves as Kena'ani.", civ_ability:"Mediterranean Colonies", created_at:"2015-04-24 01:26:47"},
{id: 34, name:"Polish", unique_unit:"Winged Hussar", unique_infrastructure:"Sukiennice", description:"The most salient feature of Poland’s topography is the extensive plain that stretches from the Baltic Sea in the north to the Carpathian Mountains to the south. Unfortunately for Poland, that plain served as the gateway for invasion—from Europe at the western borders and from Asia to the east. Poland also had the inconvenience to lie between Germany and Russia, who (for more than a millennium) cast covetous eyes on its rich lands and resources. Despite this, Poland managed to hold its own, and was once itself the biggest bully on the block.", civ_ability:"Golden Liberty", created_at:"2015-04-24 01:26:47"},
{id: 35, name:"Roman", unique_unit:"Legion", unique_infrastructure:"Bath", description:"Whether one believes Rome was founded around 750 BC by Romulus and Remus, by refugees from Troy, or by a bunch of filthy barbarians who happened to find a nice hilltop with a source of clean water nearby, for a few centuries all roads – as the saying goes – led to it. In time the patricians found that the plebeians could be kept inattentive to serious matters with bread and circuses – a truism still – and the Republic became a dictatorship, and later an Empire. Rome laid the foundation of Western civilization, and its traditions (good and bad) live on today.", civ_ability:"All Roads Lead to Rome", created_at:"2015-04-24 01:26:47"},
{id: 36, name:"Russian", unique_unit:"Cossack", unique_infrastructure:"Lavra", description:"Boyars, Cossacks, onion domes, snow-covered landscapes, the “wasteland” of Siberia, carefree serfs, stirring compositions, endless winter, and ice-chilled vodka. The romance of Russia may be appealing, but its true history is somewhat less so … especially if one listens to those serfs. With one foot in Europe and the other in Asia, Russia has influenced the course of world civilization like few other nation-states. The roots of Russia lay in the initial settlement of Novgorod by the Norse and the establishment of the Kievan Rus kingdom around 882 AD by Oleg, who managed to conquer the Ilmen Slavs, Finno-Ugris, Veps and Votes who inhabited the region – but they were all just a bunch of uncivilized savages. So, let’s begin with the rise of the Grand Duchy of Muscovy.", civ_ability:"Mother Russia", created_at:"2015-04-24 01:26:47"},
{id: 37, name:"Scottish", unique_unit:"Highlander", unique_infrastructure:"Golf Course", description:"Occupying the northernmost reaches of the island of Great Britain, Scotland’s history has long been intertwined with that of its formidable neighbor to the south. Having fought repeatedly for independence throughout its history, the nation of Scotland often found itself the object of desire for invading forces from across the world.", civ_ability:"Scottish Enlightenment", created_at:"2015-04-24 01:26:47"},
{id: 38, name:"Scythian", unique_unit:"Saka Horse Archer", unique_infrastructure:"Kurgan", description:"The Scythians were a loose (very loose) confederation of illiterate nomad-pastoralists who wandered about the steppes of Central Asia for about a thousand years. Most of what is known of them comes from a handful of ancient “historians” – the likes of the Greek Herodotus and the Roman-Greek Strabo and a few Hindu texts – and that’s not much. At their peak, the Scythians ranged across the whole of the Pontic-Caspian Steppe and beyond, from what is today the Ukraine to the borders of Manchuria. They sat astride the Silk Road, grew wealthy from the slave trade, developed a distinctive artistic style, and left civilization legends of centaurs and Amazons … but not much else.", civ_ability:"People of the Steppe", created_at:"2015-04-24 01:26:47"},
{id: 39, name:"Spanish", unique_unit:"Conquistador", unique_infrastructure:"Mission", description:"Federico Garcia Lorca wrote, “In Spain the dead are more alive than the dead of any other country in the world.” Certainly there were many of them in Spain’s bloody history. Born at the end of the Reconquista with the union of Castile and Aragon, Spain would survive devastating wars and centuries of political unrest, as well as golden ages and religious movements. From its (re)discovery and colonization of the New World, to its world-spanning empire, to its contributions to culture and the romance of life, to its involvement in countless wars, Spain is one of the few nations which can claim an encompassing influence on global civilization.", civ_ability:"Treasure Fleet", created_at:"2015-04-24 01:26:47"},
{id: 40, name:"Sumerian", unique_unit:"War-Cart", unique_infrastructure:"Ziggurat", description:"Never really a kingdom nor empire, more a collection of city-states with common customs and a sometimes central authority, Sumeria nevertheless is considered the world’s first “civilization.” Kingship (or more precisely, hegemony) came to be conferred by the priesthood, which tended to create successive short-lived dynasties from the rulers of established and influential city-states: Kish, Lagash, Ur, Uruk, Adab and so forth. At some point before 3000 BC, the Sumerians developed a written language (well, a logographic in their proto-literate period), so at least historians have some idea of what they were doing.", civ_ability:"Epic Quest", created_at:"2015-04-24 01:26:47"},
{id: 41, name:"Swedish", unique_unit:"Carolean", unique_infrastructure:"Open-Air Museum", description:"People have been living in Scandinavia since before the Neolithic period, with the region marked by a distinctive “Battle Axe Culture,” who take their name from the carved stone axes found in period graves of high-status individuals. Small bands and settlements made up the preponderance of settlements, and it was a pagan realm of Viking raiders through the end of the Western Roman Empire (Scandinavian tribes appear to have been part of the period of migration) and up through the start of the medieval period.", civ_ability:"Nobel Prize", created_at:"2015-04-24 01:26:47"},
{id: 42, name:"Zulu", unique_unit:"Impi", unique_infrastructure:"Ikanda", description:"The Zulu arose to prominence from the peoples of southern Africa, achieved dominance through force of arms, and enforced a hegemony which fundamentally changed the history of Africa. In the end, although defeated by a technologically advanced colonial power, they landed telling blows on one of the world’s most formidable military forces.", civ_ability:"Isibongo", created_at:"2015-04-24 01:26:47"}


    ])
    

    Leader.destroy_all
    Leader.create([
{id: 1, name: "Teddy Roosevelt", description: "And so it is upon your broad shoulders, Theodore Roosevelt, to charge forth and lead your people on their great adventure. Use your military might to give the peoples of your homeland the square deal they so desperately deserve. Surely you will raise America into the limelight and attract visitors from across the oceans just to see your lands. Bully for you, Mr. President..", leader_ability: "Roosevelt Corollary", leader_unit: "Rough Rider", leader_agenda: "Big Stick Policy",   created_at: "2015-04-24 01:26:47"},
{id: 2, name: "Saladin", description: "The marriage of science and religion is a delicate balancing act, but one that you have mastered, Saladin. Your quest for knowledge is noble, and your people have a deep respect for you. But you need not rush into the unknown. Given time, the answers to life's most puzzling questions will find their way back to Arabia.", leader_ability: "Righteousness of the Faith", leader_unit: "", leader_agenda: "Ayyubid Dynasty",   created_at: "2015-04-24 01:26:47"},
{id: 3, name: "John Curtin", description: "Prime Minister Curtin, you will lead Australia through challenge after challenge, and your people will emerge all the stronger for it. Others will seek friendship for your strength. If these friends prove loyal, your might and protection will carry you far. But stay vigilant, for aggression is not your natural course.", leader_ability: "Citadel of Civilization", leader_unit: "", leader_agenda: "Perpetually on Guard",   created_at: "2015-04-24 01:26:47"},
{id: 4, name: "Montezuma", description: "Tlatoani Montezuma, keep your eagle warriors happy and fed, and they will forever fight for your cause. As your Aztec empire unfurls across the land, you will never want for people to raise your walls, for you will be blessed with new, loyal workers as you conquer those around you. Go forth; Huitzilopochtli calls.", leader_ability: "Gifts for the Tlatoani", leader_unit: "", leader_agenda: "Tlatoani",   created_at: "2015-04-24 01:26:47"},
{id: 5, name: "Pedro II", description: "Your people look to you, Emperor Pedro II, to lead Brazil onto the world stage. Use your reputation as a patron of artists, scientists, and engineers to draw the greatest minds to our fertile home. For it is in the lush rainforests, teeming with life, that your people thrive. Watch them in the Carnival as they dance the samba in celebration of your great feats, Pedro the Magnanimous.", leader_ability: "Magnanimous", leader_unit: "", leader_agenda: "Patron of the Arts",   created_at: "2015-04-24 01:26:47"},
{id: 6, name: "Wilfrid Laurier", description: "You chose the sunny ways, Wilfred Laurier, and made cheerfulness and courtesy the character of the Canadian people. Where others look to divide and sow mistrust, you inspire cooperation and understanding. Show the world that a unified people can stand the test of time.", leader_ability: "The Last Best West", leader_unit: "", leader_agenda: "Canadian Expeditionary Force",   created_at: "2015-04-24 01:26:47"},
{id: 7, name: "Qin Shi Huang", description: "n your people lies your greatest strength, Emperor Qin Shi Huang. From all over the world, others will come to gaze upon the great walls and towering wonders of your united China. May the hands of your men never blister as they work hard and fast to raise the most impressive structures that the world will ever know. Protect them well, and you will forever be immortalized.", leader_ability: "The First Emperor", leader_unit: "", leader_agenda: "Wall of 10,000 Li",   created_at: "2015-04-24 01:26:47"},
{id: 8, name: "Poundmaker ", description: "Poundmaker, you bear the fate of the Cree without complaint. None doubt the skill of your warriors, but they rely upon your wisdom—striking your enemies does no good if you cannot protect your homes. As the world changes in unexpected ways, your alliances will bind you to a lasting future. Those who stand alone die alone.", leader_ability: "Favorable Terms", leader_unit: "", leader_agenda: "Iron Confederacy",   created_at: "2015-04-24 01:26:47"},
{id: 9, name: "Wilhelmina ", description: "Queen Wilhelmina, you will defend the Netherlands to the last. Turn coastland to farmland with Dutch ingenuity. Your citizens will farm with great efficiency, knowing that they are under the protection of your mighty warships. Above all, trade with everyone you meet. A good deal can turn a foe into a friend—and if not, the money will fund your opposition.", leader_ability: "Radio Oranje", leader_unit: "", leader_agenda: "Billionaire",   created_at: "2015-04-24 01:26:47"},
{id: 10, name: "Cleopatra", description: "There will be those who underestimate you, but you are cunning and full of tricks, Queen Cleopatra. Your charm will establish indestructible alliances with the strongest leaders of the world. Keep your friends close by your side and you will find yourself untouchable, with the glory of Egypt primed to win over the world.", leader_ability: "Mediterranean's Bride", leader_unit: "", leader_agenda: "Queen of the Nile",   created_at: "2015-04-24 01:26:47"},
{id: 11, name: "Victoria", description: "Your Majesty the Queen Victoria of England, extend your reach beyond your borders and across the face of the globe. Worry not over the possibility of defeat for your loyal redcoats and overwhelming navy will surely carry the day. With your calm and steady touch you can bring all lands under England's sway, establishing a true Pax Britannica.", leader_ability: "Pax Britannica", leader_unit: "Redcoat", leader_agenda: "Sun Never Sets",   created_at: "2015-04-24 01:26:47"},
{id: 12, name: "Eleanor of Aquitaine ", description: "Duchess of Aquitaine, regent of two lands, patron of troubadours, and judge of the court of love, ascend your throne again, inspire the hearts of your subjects, that they will cheer you and flock to your banners, for all who know your reign know your compassion.", leader_ability: "Court of Love", leader_unit: "", leader_agenda: "Angevin Empire",   created_at: "2015-04-24 01:26:47"},
{id: 13, name: "Catherine de Medici", description: "It falls to you, Catherine de Medici, to use your gifts of knowledge and of the arts to unite your people. Steer carefully through these troubled times, Queen Mother of France. You will build great wonders, drawing visitors from all corners of the earth. With your keen awareness of all things, both those seen and those hidden in the shadows, your empire will certainly stand the test of time.", leader_ability: "Catherine's Flying Squadron", leader_unit: "", leader_agenda: "Black Queen",   created_at: "2015-04-24 01:26:47"},
{id: 14, name: "Tamar", description: "Fierce Tamar, only a fool could misjudge Georgia's true measure. Hound your enemies with loyal clansmen who strike from the hills. Encourage your foes to dash their best against your cities' enduring walls. The armies of your protectorates will run them down as they flee. If you suffer no fools, great queen, Georgia will not suffer.", leader_ability: "Glory of the World, Kingdom and Faith", leader_unit: "", leader_agenda: "Narikala Fortress",   created_at: "2015-04-24 01:26:47"},
{id: 15, name: "Frederick Barbarossa", description: "Heroic Frederick, king of the Germans, your task is to forge the independent states that surround you into an empire. You are blessed to be a great military leader - use those skills to bring these cities under your sway so they may develop into commercial and industrial powerhouses. Surely then the bards will sing of mighty Frederick with the red beard, the great Holy Roman Emperor.", leader_ability: "Holy Roman Emperor", leader_unit: "", leader_agenda: "Iron Crown",   created_at: "2015-04-24 01:26:47"},
{id: 16, name: "Pericles", description: "Your mastery of the spoken word is a gift of great value, silver-tongued Pericles, leader of the Greeks. Through it you can attract the devotion of a league of states, surrounding yourself with their glory. Establish cultural sites along the rocky shores of Greece to unite your people behind your strong governance. If all goes well the Sirens will sing of the Age of Pericles!", leader_ability: "Surrounded by Glory", leader_unit: "", leader_agenda: "Delian League",   created_at: "2015-04-24 01:26:47"},
{id: 17, name: "Gorgo", description: "Gorgo, Queen of Sparta; glory to you and your loyal hoplite armies! Greece savors the blessings from Ares that every victory brings. And your people applaud your thoughtful governance and cultural marvels. Stand proud, for the legacy of Greece, and of your achievements, will be told over and over again for generations.", leader_ability: "Thermopylae", leader_unit: "", leader_agenda: "With Your Shield Or On It",   created_at: "2015-04-24 01:26:47"},
{id: 18, name: "Matthias Corvinus", description: "Mighty Matthias, your feats at arms are matched only by the depths of your knowledge. Let your mighty Black Army serve as your strong hand in the battlefield, both as sword against your enemies and as shield protecting your faithful people, and ages to come will utter your name in awe.", leader_ability: "Raven King", leader_unit: "Black Army", leader_agenda: "Raven Banner",   created_at: "2015-04-24 01:26:47"},
{id: 19, name: "Pachacuti", description: "Pachacuti, son of the Sun, father to a prosperous people who dwell among lofty peaks. Let the mountains be roads to you, and mighty walls for your enemies, for you grow in strength where others would starve. O, Sapa Inca who shakes the earth, show strength and diligence, and your name will shine throughout all of history.", leader_ability: "Qhapaq Ñan", leader_unit: "", leader_agenda: "Sapa Inca",   created_at: "2015-04-24 01:26:47"},
{id: 20, name: "Gandhi", description: "Be kind, Gandhi Bapu, and you will find yourself surrounded by the true friends. Keep the Indian people safe, guarding them with magnificent elephant warriors. Your faith will guide you to peace and harmony. Keep your mind open, and be the change you want to see in the world.", leader_ability: "Satyagraha", leader_unit: "", leader_agenda: "Peacekeeper",   created_at: "2015-04-24 01:26:47"},
{id: 21, name: "Chandragupta", description: "Trust your ambition, Chandragupta, for it led you to unify all of India. Unleash war elephants upon any rival who curses your name, proud Mauryan king. Once you reclaim the land for your people, your stepwells shall see it flourish. May the borders of your empire expand forever.", leader_ability: "Arthashastra", leader_unit: "", leader_agenda: "Maurya Empire",   created_at: "2015-04-24 01:26:47"},
{id: 22, name: "Gitarja", description: "Daring Gitarja, Majapahit queen of ten thousand islands, Indonesia's seas are your greatest strength. As Exalted Goddess of the Three Worlds, you shall spread your divine influence to all waters touched by the sun. Rely upon your loyal fleet, bold queen! Unleash a frightful storm upon those who bring strife to Indonesian shores.", leader_ability: "Exalted Goddess of the Three Worlds", leader_unit: "", leader_agenda: "Archipelagic State",   created_at: "2015-04-24 01:26:47"},
{id: 23, name: "Hojo Tokimune", description: "The great wave of Buddhism follows you, Shikken of Japan, Hojo Tokimune. Your people truly understand what it is to practice balance, and even your finest samurai will be well-learned and spiritually apt. Be strong, embrace the divine wind, and you will reach enlightenment.", leader_ability: "Divine Wind", leader_unit: "", leader_agenda: "Bushido",   created_at: "2015-04-24 01:26:47"},
{id: 24, name: "Jayavarman VII", description: "Wise Jayavarman, seventh to hold the name, the Khmer admire your dedication to their well-being. Your command of the land's fresh waters lets you feed your hungry people, just as it brings you ever closer to Heaven. Go forth, divine architect! Build an empire that approaches perfection—and may your enemies find their end beneath your mighty war elephants.", leader_ability: "Monasteries of the King", leader_unit: "", leader_agenda: "An End to Suffering",   created_at: "2015-04-24 01:26:47"},
{id: 25, name: "Mvemba a Nzinga", description: "Mother Earth has many gifts for you, King Mvemba a Nzinga. Your people know the dense woods and rainforests as their homes, and glide through them with ease. Great also are the gifts that come from travelers of distant lands. Keep an open mind, for the inspiration of the open world will let our people create art with power and majesty.", leader_ability: "Religious Convert", leader_unit: "", leader_agenda: "Enthusiastic Disciple",   created_at: "2015-04-24 01:26:47"},
{id: 26, name: "Seondeok", description: "Queen Seondeok, the stars reveal you lead Korea to greatness. Build Seowons to educate your people, for the secrets of the world are theirs to uncover. For those who would steal your knowledge, treat them to a rain of rocket propelled fire from your Hwacha. Reach for the heavens, shrewd queen, and your people will reach with you.", leader_ability: "Hwarang", leader_unit: "", leader_agenda: "Cheomseongdae",   created_at: "2015-04-24 01:26:47"},
{id: 27, name: "Alexander", description: "Great warlord, Alexander, beneath your sword shall Macedon spread throughout the world. Every kingdom shall be a unique challenge to overcome, but the rewards will be great if you remain true and brave. Turn away from peace, for there is no way to establish your legacy but from conquering vast lands. Charge, Alexander, and lead your people to glory!", leader_ability: "To the World's End", leader_unit: "Hetairoi", leader_agenda: "Short Life of Glory",   created_at: "2015-04-24 01:26:47"},
{id: 28, name: "Mansa Musa", description: "Mansa Musa, great king of Mali, you are blessed with wealth beyond comprehension, yet you remain uncorrupted. Raise your eyes from the marketplace to the heavens and satisfy your heart's great yearning for peace. Protect the prosperity of your people, and history will write your name in golden letters.", leader_ability: "Sahel Merchants", leader_unit: "", leader_agenda: "Lord of the Mines",   created_at: "2015-04-24 01:26:47"},
{id: 29, name: "Kupe", description: "Kupe the Navigator, you named the land of the long white cloud, and now you are called upon to settle new lands. Protect and honor the land and sea, just as your Toas protect your people. The Mа̄ori will guard the world’s natural beauty for all the ages after.", leader_ability: "Kupe's Voyage", leader_unit: "", leader_agenda: "Kaitiakitanga",   created_at: "2015-04-24 01:26:47"},
{id: 30, name: "Lautaro", description: "You did not liberate the Mapuche, young Lautaro—you inspired them to free themselves. Build totems to honor your ancestors and embolden their descendants. Such pride will fill the hearts of your cavalry as they redouble their raids into enemy lands. Stand with the Mapuche, axe-bearer, and cast a singular shadow.", leader_ability: "Swift Hawk", leader_unit: "", leader_agenda: "Spirit of Tucapel",   created_at: "2015-04-24 01:26:47"},
{id: 31, name: "Genghis Khan", description: "Genghis Khan, your cunning built Mongolia an empire from the back of your horse. Always charge to meet enemy cavalry, for a victory can draw them to your ranks. Send your swift and powerful Keshig archers to hasten your citizens across the land. Soon, the steady drumbeat of Mongolian cavalry is a sound you will teach the world.", leader_ability: "Mongol Horde", leader_unit: "", leader_agenda: "Horse Lord",   created_at: "2015-04-24 01:26:47"},
{id: 32, name: "Harald Hardrada", description: "All men fear the approach of your ships, King Harald of Norway, Thunderbolt of the North. Your longboats dominate the waves, always at the ready to unleash their berserker armies on an unsuspecting shore. May Odin bless your kingdom and may the skalds sing tales of the victories of your mighty warriors.", leader_ability: "Thunderbolt of the North", leader_unit: "", leader_agenda: "Last Viking King",   created_at: "2015-04-24 01:26:47"},
{id: 33, name: "Amanitore", description: "Amanitore, watchful Queen of Nubia, the empire you command shall claim the horizon as its border. Don't fear those who covet your abundant gold, for your archers can part their hair at five hundred paces. Your cities shall know prosperity and piety, wise queen, for the Land of the Bow honors its past as surely as it builds its own future.", leader_ability: "Kandake of Meroë", leader_unit: "", leader_agenda: "City Planner",   created_at: "2015-04-24 01:26:47"},
{id: 34, name: "Suleiman", description: "All praise to you, Suleiman the lawgiver, rightly called Magnificent! Master of the sublime house of Osman, your loyal servants stand ready to carry your commands to the farthest corner of your mighty land, while your foes tremble at the sight of your armies. Sultan of Sultans and Khan of Khans, lead your people to greatness.", leader_ability: "Grand Vizier", leader_unit: "Janissary", leader_agenda: "Lawgiver",   created_at: "2015-04-24 01:26:47"},
{id: 35, name: "Cyrus", description: "Claim the crown, Cyrus, King of Persia, for you are the anointed one. With immortal soldiers, and an unwavering faith, you will conquer and rule the peoples of the world. You may see many alliances forming around you, but do not be fooled - such is an antiquated and weak way of navigating the world. Make no promise unless it aids you in achieving your goals.", leader_ability: "Fall of Babylon", leader_unit: "", leader_agenda: "Opportunist",   created_at: "2015-04-24 01:26:47"},
{id: 36, name: "Dido", description: "Queen Dido, mother of Carthage, all your life you faced great threats and overcame them through wit and cunning. Wherever waves break on the shore, there your cities shall rise. The seas are your roads, the far horizon is your destiny and your refuge.", leader_ability: "Founder of Carthage", leader_unit: "", leader_agenda: "Sicilian Wars",   created_at: "2015-04-24 01:26:47"},
{id: 37, name: "Jadwiga", description: "Pious Jadwiga, praise be to the glory of God, the earth, and Poland! Most holy King, you will show your people the truth and the light, and they will move beyond to spread the word to others. Protected by great winged warriors, you will rise to meet any challenge you face with a devout grace unmatched by any other.", leader_ability: "Lithuanian Union", leader_unit: "", leader_agenda: "Saint",   created_at: "2015-04-24 01:26:47"},
{id: 38, name: "Trajan", description: "Cast your net wide, oh Trajan, emperor of mighty Rome. Your legions stand at the ready to march out and establish the largest empire the world has ever seen. If you can truly get all roads to lead to Rome, yours will be an empire of great riches and luxuries. Surely then our citizens will proclaim you as their best ruler, the Optimus Princeps.", leader_ability: "Trajan's Column", leader_unit: "", leader_agenda: "Optimus Princeps",   created_at: "2015-04-24 01:26:47"},
{id: 39, name: "Peter", description: "Embrace the chill winds of the Motherland, Tsar Peter. Your fascination with science and culture is a gift, and you will learn much from your Grand Embassies to other lands. Under your rule, Russia will surely flourish and spread, absorbing all that lies around it, perhaps creating the greatest land empire seen on this earth.", leader_ability: "The Grand Embassy", leader_unit: "", leader_agenda: "Westernizer",   created_at: "2015-04-24 01:26:47"},
{id: 40, name: "Robert the Bruce", description: "Robert the Bruce, as the stalwart defender of Scotland you are no stranger to war, yet rarely do you seek to inflict it. If you keep your people happy, you'll inspire them to greatness. Let anyone who takes advantage of your weaker neighbors meet your fearless highlanders. They can teach the true meaning of freedom.", leader_ability: "Bannockburn", leader_unit: "", leader_agenda: "Flower of Scotland",   created_at: "2015-04-24 01:26:47"},
{id: 41, name: "Tomyris", description: "All people will tremble with fear and respect for you, great warrior Queen Tomyris. For it is from the back of your stallion that you shall look upon and lead the Scythian people. Great epics will be told of the horse warriors that ride forth from the steppe, and at the front line of every battle - they will find you. Ride on, fierce queen, and may your friends be true just as your enemies falter.", leader_ability: "Killer of Cyrus", leader_unit: "", leader_agenda: "Backstab Averse",   created_at: "2015-04-24 01:26:47"},
{id: 42, name: "Philip II", description: "All Spain stands ready to answer your prayers, devout King Philip II. From your palace at El Escorial you can send forth your followers: missionaries, apostles, and conquistadors ready to strike out across the seas to spread the good word about your most holy empire. May the treasures they uncover fuel your quest to unite the world under one faith and one empire, making you truly the Most Catholic king.", leader_ability: "El Escorial", leader_unit: "", leader_agenda: "Counter Reformer",   created_at: "2015-04-24 01:26:47"},
{id: 43, name: "Gilgamesh", description: "Much rests upon your shoulders, King Gilgamesh. Your own people, and many people of the world, look to you as leader. But you are more than a mere man, and the weight of the world will never cause you to waver. Encourage the people of Sumer to settle the fertile lands along rivers, and be sure to choose your allies carefully - for there will be many vying for a piece of your strength. Venture forth, for it is time to begin your epic tale.", leader_ability: "Adventures of Enkidu", leader_unit: "", leader_agenda: "Ally of Enkidu",   created_at: "2015-04-24 01:26:47"},
{id: 44, name: "Kristina", description: "Minerva of the North, unmatched in learning and wisdom, you chose a life of culture over that of power. Light up your kingdom with art and music. Let Sweden be the guiding star for other civilizations to follow. Once more the world has a need for great patrons of the arts and culture—and it looks to you.", leader_ability: "Minerva of the North", leader_unit: "", leader_agenda: "Bibliophile",   created_at: "2015-04-24 01:26:47"},
{id: 45, name: "Shaka", description: "Clever Shaka, king of the Zulu, your soldiers shall win you an empire. The Impi warriors at your command outflank and outfight all who oppose them. The unyielding Zulu armies will prove your strength lies in numbers. You need not war with every neighbor—but let them think you might.", leader_ability: "Amabutho", leader_unit: "", leader_agenda: "Horn, Chest, Loins",   created_at: "2015-04-24 01:26:47"}

    ])
    
    Faction.destroy_all
    Faction.create([
      {id: 1, civ_id: 1, leader_id: 1, dom_score_land: 8, dom_score_water: 6, dom_def_land: 10, dom_def_water: 8, sci_score_land: 4, sci_score_water: 3, sci_def_land: 4, sci_def_water: 3, cul_score_land: 10, cul_score_water: 8, cul_def_land: 8, cul_def_water: 6,  rel_score_land: 4, rel_score_water: 4, rel_def_land: 4, rel_def_water: 4,  dip_score_land: 8, dip_score_water: 8, dip_def_land: 8, dip_def_water: 8, created_at: "2015-04-24 01:26:47"},
{id: 2, civ_id: 2, leader_id: 2, dom_score_land: 6, dom_score_water: 4, dom_def_land: 6, dom_def_water: 4, sci_score_land: 10, sci_score_water: 10, sci_def_land: 6, sci_def_water: 4, cul_score_land: 4, cul_score_water: 4, cul_def_land: 6, cul_def_water: 6,  rel_score_land: 10, rel_score_water: 10, rel_def_land: 10, rel_def_water: 10,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 4, dip_def_water: 4, created_at: "2015-04-24 01:26:47"},
{id: 3, civ_id: 3, leader_id: 3, dom_score_land: 6, dom_score_water: 8, dom_def_land: 10, dom_def_water: 10, sci_score_land: 10, sci_score_water: 10, sci_def_land: 8, sci_def_water: 8, cul_score_land: 4, cul_score_water: 6, cul_def_land: 6, cul_def_water: 6,  rel_score_land: 4, rel_score_water: 4, rel_def_land: 4, rel_def_water: 4,  dip_score_land: 4, dip_score_water: 4, dip_def_land: 4, dip_def_water: 4, created_at: "2015-04-24 01:26:47"},
{id: 4, civ_id: 4, leader_id: 4, dom_score_land: 10, dom_score_water: 8, dom_def_land: 10, dom_def_water: 8, sci_score_land: 3, sci_score_water: 3, sci_def_land: 6, sci_def_water: 4, cul_score_land: 3, cul_score_water: 3, cul_def_land: 6, cul_def_water: 4,  rel_score_land: 3, rel_score_water: 3, rel_def_land: 6, rel_def_water: 4,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 6, dip_def_water: 4, created_at: "2015-04-24 01:26:47"},
{id: 5, civ_id: 5, leader_id: 5, dom_score_land: 3, dom_score_water: 10, dom_def_land: 3, dom_def_water: 8, sci_score_land: 4, sci_score_water: 4, sci_def_land: 3, sci_def_water: 8, cul_score_land: 8, cul_score_water: 8, cul_def_land: 6, cul_def_water: 10,  rel_score_land: 4, rel_score_water: 3, rel_def_land: 3, rel_def_water: 6,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 3, dip_def_water: 6, created_at: "2015-04-24 01:26:47"},
{id: 6, civ_id: 6, leader_id: 6, dom_score_land: 0, dom_score_water: 0, dom_def_land: 6, dom_def_water: 6, sci_score_land: 3, sci_score_water: 3, sci_def_land: 3, sci_def_water: 3, cul_score_land: 8, cul_score_water: 6, cul_def_land: 4, cul_def_water: 4,  rel_score_land: 3, rel_score_water: 3, rel_def_land: 3, rel_def_water: 3,  dip_score_land: 8, dip_score_water: 8, dip_def_land: 8, dip_def_water: 8, created_at: "2015-04-24 01:26:47"},
{id: 7, civ_id: 7, leader_id: 7, dom_score_land: 3, dom_score_water: 3, dom_def_land: 8, dom_def_water: 3, sci_score_land: 8, sci_score_water: 6, sci_def_land: 4, sci_def_water: 4, cul_score_land: 10, cul_score_water: 8, cul_def_land: 6, cul_def_water: 4,  rel_score_land: 4, rel_score_water: 4, rel_def_land: 4, rel_def_water: 4,  dip_score_land: 4, dip_score_water: 4, dip_def_land: 4, dip_def_water: 4, created_at: "2015-04-24 01:26:47"},
{id: 8, civ_id: 8, leader_id: 8, dom_score_land: 4, dom_score_water: 4, dom_def_land: 4, dom_def_water: 4, sci_score_land: 6, sci_score_water: 6, sci_def_land: 3, sci_def_water: 3, cul_score_land: 6, cul_score_water: 6, cul_def_land: 6, cul_def_water: 6,  rel_score_land: 4, rel_score_water: 4, rel_def_land: 4, rel_def_water: 4,  dip_score_land: 6, dip_score_water: 6, dip_def_land: 4, dip_def_water: 4, created_at: "2015-04-24 01:26:47"},
{id: 9, civ_id: 9, leader_id: 9, dom_score_land: 4, dom_score_water: 8, dom_def_land: 4, dom_def_water: 8, sci_score_land: 6, sci_score_water: 6, sci_def_land: 6, sci_def_water: 8, cul_score_land: 6, cul_score_water: 6, cul_def_land: 6, cul_def_water: 8,  rel_score_land: 3, rel_score_water: 4, rel_def_land: 3, rel_def_water: 4,  dip_score_land: 6, dip_score_water: 6, dip_def_land: 4, dip_def_water: 4, created_at: "2015-04-24 01:26:47"},
{id: 10, civ_id: 10, leader_id: 10, dom_score_land: 6, dom_score_water: 3, dom_def_land: 6, dom_def_water: 3, sci_score_land: 3, sci_score_water: 3, sci_def_land: 3, sci_def_water: 3, cul_score_land: 10, cul_score_water: 8, cul_def_land: 6, cul_def_water: 4,  rel_score_land: 8, rel_score_water: 8, rel_def_land: 6, rel_def_water: 6,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 3, dip_def_water: 3, created_at: "2015-04-24 01:26:47"},
{id: 11, civ_id: 11, leader_id: 11, dom_score_land: 8, dom_score_water: 10, dom_def_land: 6, dom_def_water: 8, sci_score_land: 3, sci_score_water: 3, sci_def_land: 6, sci_def_water: 8, cul_score_land: 3, cul_score_water: 3, cul_def_land: 6, cul_def_water: 8,  rel_score_land: 3, rel_score_water: 3, rel_def_land: 6, rel_def_water: 8,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 4, dip_def_water: 6, created_at: "2015-04-24 01:26:47"},
{id: 12, civ_id: 11, leader_id: 12, dom_score_land: 6, dom_score_water: 8, dom_def_land: 4, dom_def_water: 6, sci_score_land: 3, sci_score_water: 3, sci_def_land: 4, sci_def_water: 6, cul_score_land: 6, cul_score_water: 6, cul_def_land: 4, cul_def_water: 6,  rel_score_land: 3, rel_score_water: 3, rel_def_land: 4, rel_def_water: 6,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 4, dip_def_water: 4, created_at: "2015-04-24 01:26:47"},
{id: 13, civ_id: 12, leader_id: 12, dom_score_land: 6, dom_score_water: 4, dom_def_land: 6, dom_def_water: 3, sci_score_land: 3, sci_score_water: 3, sci_def_land: 3, sci_def_water: 3, cul_score_land: 6, cul_score_water: 6, cul_def_land: 4, cul_def_water: 4,  rel_score_land: 3, rel_score_water: 3, rel_def_land: 3, rel_def_water: 3,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 3, dip_def_water: 3, created_at: "2015-04-24 01:26:47"},
{id: 14, civ_id: 12, leader_id: 13, dom_score_land: 4, dom_score_water: 3, dom_def_land: 6, dom_def_water: 3, sci_score_land: 3, sci_score_water: 3, sci_def_land: 6, sci_def_water: 6, cul_score_land: 10, cul_score_water: 8, cul_def_land: 6, cul_def_water: 4,  rel_score_land: 3, rel_score_water: 3, rel_def_land: 3, rel_def_water: 3,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 3, dip_def_water: 3, created_at: "2015-04-24 01:26:47"},
{id: 15, civ_id: 13, leader_id: 14, dom_score_land: 6, dom_score_water: 3, dom_def_land: 6, dom_def_water: 3, sci_score_land: 3, sci_score_water: 3, sci_def_land: 3, sci_def_water: 3, cul_score_land: 3, cul_score_water: 3, cul_def_land: 3, cul_def_water: 3,  rel_score_land: 8, rel_score_water: 8, rel_def_land: 8, rel_def_water: 8,  dip_score_land: 8, dip_score_water: 8, dip_def_land: 8, dip_def_water: 8, created_at: "2015-04-24 01:26:47"},
{id: 16, civ_id: 14, leader_id: 15, dom_score_land: 8, dom_score_water: 8, dom_def_land: 6, dom_def_water: 8, sci_score_land: 8, sci_score_water: 8, sci_def_land: 6, sci_def_water: 8, cul_score_land: 4, cul_score_water: 4, cul_def_land: 6, cul_def_water: 6,  rel_score_land: 3, rel_score_water: 3, rel_def_land: 6, rel_def_water: 6,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 8, dip_def_water: 8, created_at: "2015-04-24 01:26:47"},
{id: 17, civ_id: 15, leader_id: 16, dom_score_land: 4, dom_score_water: 3, dom_def_land: 4, dom_def_water: 3, sci_score_land: 3, sci_score_water: 3, sci_def_land: 3, sci_def_water: 3, cul_score_land: 10, cul_score_water: 8, cul_def_land: 10, cul_def_water: 10,  rel_score_land: 3, rel_score_water: 3, rel_def_land: 3, rel_def_water: 3,  dip_score_land: 10, dip_score_water: 10, dip_def_land: 10, dip_def_water: 10, created_at: "2015-04-24 01:26:47"},
{id: 18, civ_id: 15, leader_id: 17, dom_score_land: 6, dom_score_water: 3, dom_def_land: 6, dom_def_water: 3, sci_score_land: 3, sci_score_water: 3, sci_def_land: 3, sci_def_water: 3, cul_score_land: 8, cul_score_water: 6, cul_def_land: 8, cul_def_water: 8,  rel_score_land: 3, rel_score_water: 3, rel_def_land: 3, rel_def_water: 3,  dip_score_land: 6, dip_score_water: 6, dip_def_land: 6, dip_def_water: 6, created_at: "2015-04-24 01:26:47"},
{id: 19, civ_id: 16, leader_id: 18, dom_score_land: 10, dom_score_water: 8, dom_def_land: 8, dom_def_water: 6, sci_score_land: 4, sci_score_water: 4, sci_def_land: 6, sci_def_water: 6, cul_score_land: 4, cul_score_water: 4, cul_def_land: 6, cul_def_water: 6,  rel_score_land: 4, rel_score_water: 4, rel_def_land: 6, rel_def_water: 6,  dip_score_land: 10, dip_score_water: 10, dip_def_land: 10, dip_def_water: 10, created_at: "2015-04-24 01:26:47"},
{id: 20, civ_id: 17, leader_id: 19, dom_score_land: 4, dom_score_water: 3, dom_def_land: 6, dom_def_water: 4, sci_score_land: 8, sci_score_water: 8, sci_def_land: 4, sci_def_water: 4, cul_score_land: 4, cul_score_water: 4, cul_def_land: 4, cul_def_water: 4,  rel_score_land: 4, rel_score_water: 3, rel_def_land: 4, rel_def_water: 3,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 3, dip_def_water: 3, created_at: "2015-04-24 01:26:47"},
{id: 21, civ_id: 18, leader_id: 20, dom_score_land: 3, dom_score_water: 3, dom_def_land: 3, dom_def_water: 3, sci_score_land: 3, sci_score_water: 3, sci_def_land: 3, sci_def_water: 3, cul_score_land: 3, cul_score_water: 3, cul_def_land: 3, cul_def_water: 3,  rel_score_land: 8, rel_score_water: 8, rel_def_land: 8, rel_def_water: 8,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 3, dip_def_water: 3, created_at: "2015-04-24 01:26:47"},
{id: 22, civ_id: 18, leader_id: 21, dom_score_land: 8, dom_score_water: 4, dom_def_land: 4, dom_def_water: 3, sci_score_land: 3, sci_score_water: 3, sci_def_land: 3, sci_def_water: 3, cul_score_land: 3, cul_score_water: 3, cul_def_land: 6, cul_def_water: 4,  rel_score_land: 6, rel_score_water: 6, rel_def_land: 8, rel_def_water: 6,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 3, dip_def_water: 3, created_at: "2015-04-24 01:26:47"},
{id: 23, civ_id: 19, leader_id: 22, dom_score_land: 3, dom_score_water: 8, dom_def_land: 3, dom_def_water: 6, sci_score_land: 3, sci_score_water: 6, sci_def_land: 3, sci_def_water: 6, cul_score_land: 4, cul_score_water: 8, cul_def_land: 4, cul_def_water: 8,  rel_score_land: 6, rel_score_water: 10, rel_def_land: 6, rel_def_water: 10,  dip_score_land: 3, dip_score_water: 4, dip_def_land: 3, dip_def_water: 6, created_at: "2015-04-24 01:26:47"},
{id: 24, civ_id: 20, leader_id: 23, dom_score_land: 8, dom_score_water: 8, dom_def_land: 8, dom_def_water: 8, sci_score_land: 8, sci_score_water: 8, sci_def_land: 6, sci_def_water: 6, cul_score_land: 8, cul_score_water: 8, cul_def_land: 6, cul_def_water: 6,  rel_score_land: 6, rel_score_water: 6, rel_def_land: 6, rel_def_water: 6,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 4, dip_def_water: 4, created_at: "2015-04-24 01:26:47"},
{id: 25, civ_id: 21, leader_id: 24, dom_score_land: 4, dom_score_water: 3, dom_def_land: 3, dom_def_water: 3, sci_score_land: 4, sci_score_water: 3, sci_def_land: 3, sci_def_water: 3, cul_score_land: 8, cul_score_water: 8, cul_def_land: 4, cul_def_water: 4,  rel_score_land: 8, rel_score_water: 8, rel_def_land: 10, rel_def_water: 10,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 3, dip_def_water: 3, created_at: "2015-04-24 01:26:47"},
{id: 26, civ_id: 22, leader_id: 25, dom_score_land: 4, dom_score_water: 3, dom_def_land: 6, dom_def_water: 4, sci_score_land: 6, sci_score_water: 6, sci_def_land: 4, sci_def_water: 3, cul_score_land: 10, cul_score_water: 6, cul_def_land: 8, cul_def_water: 6,  rel_score_land: 0, rel_score_water: 0, rel_def_land: 0, rel_def_water: 0,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 3, dip_def_water: 3, created_at: "2015-04-24 01:26:47"},
{id: 27, civ_id: 23, leader_id: 26, dom_score_land: 4, dom_score_water: 4, dom_def_land: 8, dom_def_water: 6, sci_score_land: 10, sci_score_water: 10, sci_def_land: 8, sci_def_water: 8, cul_score_land: 4, cul_score_water: 4, cul_def_land: 6, cul_def_water: 6,  rel_score_land: 3, rel_score_water: 3, rel_def_land: 3, rel_def_water: 3,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 3, dip_def_water: 3, created_at: "2015-04-24 01:26:47"},
{id: 28, civ_id: 24, leader_id: 27, dom_score_land: 10, dom_score_water: 8, dom_def_land: 8, dom_def_water: 8, sci_score_land: 6, sci_score_water: 8, sci_def_land: 10, sci_def_water: 8, cul_score_land: 4, cul_score_water: 3, cul_def_land: 6, cul_def_water: 6,  rel_score_land: 3, rel_score_water: 3, rel_def_land: 6, rel_def_water: 6,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 4, dip_def_water: 4, created_at: "2015-04-24 01:26:47"},
{id: 29, civ_id: 25, leader_id: 28, dom_score_land: 6, dom_score_water: 6, dom_def_land: 6, dom_def_water: 6, sci_score_land: 8, sci_score_water: 8, sci_def_land: 4, sci_def_water: 4, cul_score_land: 4, cul_score_water: 4, cul_def_land: 4, cul_def_water: 4,  rel_score_land: 10, rel_score_water: 10, rel_def_land: 10, rel_def_water: 10,  dip_score_land: 6, dip_score_water: 6, dip_def_land: 4, dip_def_water: 4, created_at: "2015-04-24 01:26:47"},
{id: 30, civ_id: 26, leader_id: 29, dom_score_land: 3, dom_score_water: 4, dom_def_land: 3, dom_def_water: 6, sci_score_land: 3, sci_score_water: 4, sci_def_land: 3, sci_def_water: 4, cul_score_land: 8, cul_score_water: 10, cul_def_land: 8, cul_def_water: 10,  rel_score_land: 3, rel_score_water: 4, rel_def_land: 3, rel_def_water: 4,  dip_score_land: 3, dip_score_water: 4, dip_def_land: 3, dip_def_water: 4, created_at: "2015-04-24 01:26:47"},
{id: 31, civ_id: 27, leader_id: 30, dom_score_land: 8, dom_score_water: 6, dom_def_land: 6, dom_def_water: 6, sci_score_land: 3, sci_score_water: 3, sci_def_land: 6, sci_def_water: 4, cul_score_land: 8, cul_score_water: 6, cul_def_land: 8, cul_def_water: 6,  rel_score_land: 4, rel_score_water: 4, rel_def_land: 6, rel_def_water: 4,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 4, dip_def_water: 3, created_at: "2015-04-24 01:26:47"},
{id: 32, civ_id: 28, leader_id: 31, dom_score_land: 10, dom_score_water: 6, dom_def_land: 8, dom_def_water: 6, sci_score_land: 3, sci_score_water: 3, sci_def_land: 6, sci_def_water: 4, cul_score_land: 3, cul_score_water: 3, cul_def_land: 6, cul_def_water: 4,  rel_score_land: 3, rel_score_water: 3, rel_def_land: 6, rel_def_water: 4,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 3, dip_def_water: 3, created_at: "2015-04-24 01:26:47"},
{id: 33, civ_id: 29, leader_id: 32, dom_score_land: 6, dom_score_water: 8, dom_def_land: 4, dom_def_water: 8, sci_score_land: 3, sci_score_water: 4, sci_def_land: 3, sci_def_water: 6, cul_score_land: 3, cul_score_water: 4, cul_def_land: 3, cul_def_water: 6,  rel_score_land: 3, rel_score_water: 4, rel_def_land: 3, rel_def_water: 4,  dip_score_land: 3, dip_score_water: 4, dip_def_land: 3, dip_def_water: 4, created_at: "2015-04-24 01:26:47"},
{id: 34, civ_id: 30, leader_id: 33, dom_score_land: 8, dom_score_water: 4, dom_def_land: 8, dom_def_water: 4, sci_score_land: 4, sci_score_water: 4, sci_def_land: 4, sci_def_water: 4, cul_score_land: 4, cul_score_water: 4, cul_def_land: 4, cul_def_water: 4,  rel_score_land: 4, rel_score_water: 4, rel_def_land: 4, rel_def_water: 4,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 4, dip_def_water: 4, created_at: "2015-04-24 01:26:47"},
{id: 35, civ_id: 31, leader_id: 34, dom_score_land: 10, dom_score_water: 8, dom_def_land: 8, dom_def_water: 8, sci_score_land: 3, sci_score_water: 3, sci_def_land: 6, sci_def_water: 6, cul_score_land: 3, cul_score_water: 3, cul_def_land: 6, cul_def_water: 6,  rel_score_land: 3, rel_score_water: 3, rel_def_land: 6, rel_def_water: 6,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 4, dip_def_water: 4, created_at: "2015-04-24 01:26:47"},
{id: 36, civ_id: 32, leader_id: 35, dom_score_land: 10, dom_score_water: 8, dom_def_land: 10, dom_def_water: 4, sci_score_land: 3, sci_score_water: 3, sci_def_land: 6, sci_def_water: 4, cul_score_land: 8, cul_score_water: 8, cul_def_land: 10, cul_def_water: 6,  rel_score_land: 6, rel_score_water: 6, rel_def_land: 8, rel_def_water: 6,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 6, dip_def_water: 4, created_at: "2015-04-24 01:26:47"},
{id: 37, civ_id: 33, leader_id: 36, dom_score_land: 3, dom_score_water: 4, dom_def_land: 3, dom_def_water: 6, sci_score_land: 6, sci_score_water: 10, sci_def_land: 4, sci_def_water: 6, cul_score_land: 3, cul_score_water: 4, cul_def_land: 3, cul_def_water: 4,  rel_score_land: 3, rel_score_water: 4, rel_def_land: 3, rel_def_water: 4,  dip_score_land: 4, dip_score_water: 4, dip_def_land: 4, dip_def_water: 4, created_at: "2015-04-24 01:26:47"},
{id: 38, civ_id: 34, leader_id: 37, dom_score_land: 8, dom_score_water: 4, dom_def_land: 6, dom_def_water: 4, sci_score_land: 3, sci_score_water: 3, sci_def_land: 4, sci_def_water: 3, cul_score_land: 6, cul_score_water: 4, cul_def_land: 6, cul_def_water: 4,  rel_score_land: 6, rel_score_water: 6, rel_def_land: 6, rel_def_water: 6,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 3, dip_def_water: 3, created_at: "2015-04-24 01:26:47"},
{id: 39, civ_id: 35, leader_id: 38, dom_score_land: 6, dom_score_water: 4, dom_def_land: 8, dom_def_water: 4, sci_score_land: 6, sci_score_water: 6, sci_def_land: 6, sci_def_water: 4, cul_score_land: 6, cul_score_water: 6, cul_def_land: 6, cul_def_water: 4,  rel_score_land: 4, rel_score_water: 4, rel_def_land: 6, rel_def_water: 4,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 4, dip_def_water: 3, created_at: "2015-04-24 01:26:47"},
{id: 40, civ_id: 36, leader_id: 39, dom_score_land: 6, dom_score_water: 4, dom_def_land: 8, dom_def_water: 4, sci_score_land: 4, sci_score_water: 4, sci_def_land: 3, sci_def_water: 3, cul_score_land: 10, cul_score_water: 10, cul_def_land: 8, cul_def_water: 8,  rel_score_land: 10, rel_score_water: 10, rel_def_land: 10, rel_def_water: 10,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 3, dip_def_water: 3, created_at: "2015-04-24 01:26:47"},
{id: 41, civ_id: 37, leader_id: 40, dom_score_land: 8, dom_score_water: 4, dom_def_land: 6, dom_def_water: 6, sci_score_land: 8, sci_score_water: 8, sci_def_land: 8, sci_def_water: 8, cul_score_land: 6, cul_score_water: 6, cul_def_land: 4, cul_def_water: 4,  rel_score_land: 3, rel_score_water: 3, rel_def_land: 4, rel_def_water: 4,  dip_score_land: 4, dip_score_water: 4, dip_def_land: 4, dip_def_water: 4, created_at: "2015-04-24 01:26:47"},
{id: 42, civ_id: 38, leader_id: 41, dom_score_land: 8, dom_score_water: 6, dom_def_land: 6, dom_def_water: 4, sci_score_land: 3, sci_score_water: 3, sci_def_land: 6, sci_def_water: 3, cul_score_land: 3, cul_score_water: 3, cul_def_land: 6, cul_def_water: 4,  rel_score_land: 6, rel_score_water: 6, rel_def_land: 8, rel_def_water: 6,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 3, dip_def_water: 3, created_at: "2015-04-24 01:26:47"},
{id: 43, civ_id: 39, leader_id: 42, dom_score_land: 6, dom_score_water: 6, dom_def_land: 6, dom_def_water: 6, sci_score_land: 4, sci_score_water: 6, sci_def_land: 4, sci_def_water: 6, cul_score_land: 3, cul_score_water: 3, cul_def_land: 4, cul_def_water: 4,  rel_score_land: 8, rel_score_water: 8, rel_def_land: 6, rel_def_water: 8,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 3, dip_def_water: 3, created_at: "2015-04-24 01:26:47"},
{id: 44, civ_id: 40, leader_id: 43, dom_score_land: 8, dom_score_water: 4, dom_def_land: 6, dom_def_water: 4, sci_score_land: 6, sci_score_water: 6, sci_def_land: 6, sci_def_water: 4, cul_score_land: 3, cul_score_water: 3, cul_def_land: 6, cul_def_water: 4,  rel_score_land: 4, rel_score_water: 4, rel_def_land: 6, rel_def_water: 4,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 3, dip_def_water: 3, created_at: "2015-04-24 01:26:47"},
{id: 45, civ_id: 41, leader_id: 44, dom_score_land: 4, dom_score_water: 4, dom_def_land: 4, dom_def_water: 4, sci_score_land: 4, sci_score_water: 4, sci_def_land: 4, sci_def_water: 4, cul_score_land: 10, cul_score_water: 10, cul_def_land: 8, cul_def_water: 8,  rel_score_land: 3, rel_score_water: 3, rel_def_land: 3, rel_def_water: 3,  dip_score_land: 10, dip_score_water: 10, dip_def_land: 10, dip_def_water: 10, created_at: "2015-04-24 01:26:47"},
{id: 46, civ_id: 42, leader_id: 45, dom_score_land: 10, dom_score_water: 6, dom_def_land: 8, dom_def_water: 4, sci_score_land: 3, sci_score_water: 3, sci_def_land: 6, sci_def_water: 3, cul_score_land: 3, cul_score_water: 3, cul_def_land: 6, cul_def_water: 3,  rel_score_land: 3, rel_score_water: 3, rel_def_land: 6, rel_def_water: 3,  dip_score_land: 3, dip_score_water: 3, dip_def_land: 3, dip_def_water: 3, created_at: "2015-04-24 01:26:47"}

    ])    
    
    Map.destroy_all
    Map.create([
      {id: 1, name: "Continents", land_weight: 0.6, water_weight: 0.4, created_at: "2015-04-24 01:26:47"},  
      {id: 2, name: "Pangaea", land_weight: 0.8, water_weight: 0.2, created_at: "2015-04-24 01:26:47"},
      {id: 3, name: "Inland Sea", land_weight: 0.5, water_weight: 0.5, created_at: "2015-04-24 01:26:47"},  
      {id: 4, name: "Island Plates", land_weight: 0.3, water_weight: 0.7, created_at: "2015-04-24 01:26:47"},    
      {id: 5, name: "Fractals", land_weight: 0.5, water_weight: 0.5, created_at: "2015-04-24 01:26:47"},     
      
    ])
    
    ending = Time.now
    elapsed = ending - starting

    puts "#{elapsed.to_i} seconds elapsed."    
    # Write some Ruby to quickly create some records in your tables.
    # If it's helpful, you can use methods from the Faker gem for random data:
    #   https://github.com/stympy/faker

  end
end
